- hosts: 5.161.90.22
  vars: 
    git_repo: 'https://github.com/gileadraab/phoebesnotebook.git'
    folder_project_destination: /home/mysite/
    requirements_path: /home/mysite/requirements.txt
    venv_path: /home/mysite/venv
    service_file: mysite.service
    block_configuration_file: mySiteBlockConfiguration
    
  user: root
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install the package "python3.8-venv"
      ansible.builtin.apt:
        name: python3.8-venv

    - name: Get repository from git and update locally
      ansible.builtin.git:
        repo: "{{git_repo}}"
        dest: "{{folder_project_destination}}"
        version: "gilead"
        clone: yes
        update: yes

    - name: Install specified python requirements in indicated virtualenv
      ansible.builtin.pip:
        virtualenv_command: python3 -m venv
        requirements: "{{requirements_path}}"
        virtualenv: "{{venv_path}}"
    
    - name: Copy service file with owner and permissions to server
      ansible.builtin.copy:
        src: "{{service_file}}"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0777'

    - name: Start gunicorn service
      systemd:
        name: "{{service_file}}"
        state: restarted
        daemon_reload: yes

    - name: Enable gunicorn service
      systemd:
        name: "{{service_file}}"
        enabled: true

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx

    - name: alow ssh
      community.general.ufw:
        name: "{{item}}"
        rule: allow
      loop:
        - OpenSSH
        - Nginx Full
    
    - name: enable UFW
      community.general.ufw:
        state: reloaded

    - name: Copy server block configuration file to server
      ansible.builtin.copy:
        src: "{{block_configuration_file}}"
        dest: /etc/nginx/sites-available/{{block_configuration_file}}
        owner: root
        group: root
        mode: '0777'   

    - name: Creating a symlink between sites-available and sites-enabled directories
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{block_configuration_file}}
        dest: /etc/nginx/sites-enabled/{{block_configuration_file}}
        state: link 
    
    - name: Start nginx
      systemd:
        name: nginx
        state: restarted
    

      

    
