- hosts: 5.161.66.182
  user: root
  tasks:
    - name: Get repository from git and update locally
      ansible.builtin.git:
        repo: 'https://github.com/gileadraab/mysite.git'
        dest: /home/gileadraab/mysite/test
        clone: yes
        update: yes
